tagFormat: "${version}"
branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - { name: "master", prerelease: false }
    - { name: "next", prerelease: true, channel: "next" }
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - "@semantic-release/npm"
    - - "@semantic-release/git"
      - assets:
            - CHANGELOG.md
            - package.json
            - package-lock.json
    - - "@saithodev/semantic-release-backmerge"
      - branches:
            - { from: "master", to: "next" }
